# Generated by Django 3.2 on 2024-01-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=255)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.CharField(max_length=255)),
                ('agency_timezone', models.CharField(max_length=255)),
                ('agency_lang', models.CharField(max_length=255)),
                ('agency_phone', models.CharField(max_length=255, null=True)),
                ('agency_fare_url', models.CharField(max_length=255, null=True)),
                ('agency_email', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=255)),
                ('monday', models.IntegerField()),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('saturday', models.IntegerField()),
                ('sunday', models.IntegerField()),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fare_Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_id', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency_type', models.CharField(max_length=255)),
                ('payment_method', models.IntegerField()),
                ('transfers', models.IntegerField()),
                ('transfer_duration', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office_jp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.CharField(max_length=255)),
                ('office_name', models.CharField(max_length=255)),
                ('office_url', models.CharField(max_length=255, null=True)),
                ('office_phone', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=255)),
                ('agency_id', models.CharField(max_length=255)),
                ('route_short_name', models.CharField(max_length=255, null=True)),
                ('route_long_name', models.CharField(max_length=255, null=True)),
                ('route_desc', models.CharField(max_length=255, null=True)),
                ('route_type', models.IntegerField(null=True)),
                ('route_url', models.CharField(max_length=255, null=True)),
                ('route_color', models.CharField(max_length=255, null=True)),
                ('route_text_color', models.CharField(max_length=255, null=True)),
                ('agency_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
            ],
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=255)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=255)),
                ('stop_code', models.CharField(max_length=255, null=True)),
                ('stop_name', models.CharField(max_length=255, null=True)),
                ('stop_desc', models.CharField(max_length=255, null=True)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('zone_id', models.CharField(max_length=255, null=True)),
                ('stop_url', models.CharField(max_length=255, null=True)),
                ('location_type', models.IntegerField(default=0, null=True)),
                ('parent_station', models.CharField(max_length=255, null=True)),
                ('wheelchair_boarding', models.IntegerField(null=True)),
                ('platform_code', models.CharField(max_length=255, null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=255)),
                ('route_id', models.CharField(max_length=255)),
                ('service_id', models.CharField(max_length=255)),
                ('trip_headsign', models.CharField(max_length=255, null=True)),
                ('trip_short_name', models.CharField(max_length=255, null=True)),
                ('direction_id', models.IntegerField(null=True)),
                ('block_id', models.CharField(max_length=255, null=True)),
                ('shape_id', models.CharField(max_length=255, null=True)),
                ('wheelchair_accessible', models.IntegerField(null=True)),
                ('bikes_allowed', models.IntegerField(null=True)),
                ('jp_trip_desc', models.CharField(max_length=255, null=True)),
                ('jp_trip_desc_symbol', models.CharField(max_length=255, null=True)),
                ('jp_office_id', models.CharField(max_length=255, null=True)),
                ('jp_office_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.office_jp')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
                ('route_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routes')),
                ('service_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calendar')),
                ('shapes', models.ManyToManyField(blank=True, to='api.Shapes')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_id', models.CharField(max_length=255)),
                ('to_stop_id', models.CharField(max_length=255)),
                ('transfer_type', models.IntegerField()),
                ('min_transfer_time', models.IntegerField(null=True)),
                ('from_stop_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop', to='api.stops')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
                ('to_stop_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stop', to='api.stops')),
            ],
        ),
        migrations.CreateModel(
            name='Stop_Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=255)),
                ('arrival_time', models.CharField(max_length=255)),
                ('departure_time', models.CharField(max_length=255)),
                ('stop_id', models.CharField(max_length=255)),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(max_length=255, null=True)),
                ('pickup_type', models.IntegerField(null=True)),
                ('drop_off_type', models.IntegerField(null=True)),
                ('timepoint', models.IntegerField(null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
                ('stop_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stops')),
                ('trip_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trips')),
            ],
        ),
        migrations.CreateModel(
            name='Routes_jp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=255)),
                ('route_update_date', models.CharField(max_length=255, null=True)),
                ('origin_stop', models.CharField(max_length=255, null=True)),
                ('via_stop', models.CharField(max_length=255, null=True)),
                ('destination_stop', models.CharField(max_length=255, null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
                ('route_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routes')),
            ],
        ),
        migrations.AddField(
            model_name='office_jp',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant'),
        ),
        migrations.CreateModel(
            name='Frequencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('headway_secs', models.IntegerField()),
                ('exact_times', models.IntegerField(null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
                ('trip_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trips')),
            ],
        ),
        migrations.CreateModel(
            name='Feed_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_publisher_name', models.CharField(max_length=255)),
                ('feed_publisher_url', models.CharField(max_length=255)),
                ('feed_lang', models.CharField(max_length=255)),
                ('feed_start_date', models.CharField(max_length=255, null=True)),
                ('feed_end_date', models.CharField(max_length=255, null=True)),
                ('feed_version', models.CharField(max_length=255, null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
            ],
        ),
        migrations.CreateModel(
            name='Fare_Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_id', models.CharField(max_length=255)),
                ('route_id', models.CharField(max_length=255, null=True)),
                ('origin_id', models.CharField(max_length=255, null=True)),
                ('destination_id', models.CharField(max_length=255, null=True)),
                ('destination_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='api.stops')),
                ('fare_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fare_attributes')),
                ('origin_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='api.stops')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
                ('route_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.routes')),
            ],
        ),
        migrations.AddField(
            model_name='fare_attributes',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant'),
        ),
        migrations.CreateModel(
            name='Calendar_Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('exception_type', models.IntegerField()),
                ('calendar_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calendar')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant'),
        ),
        migrations.CreateModel(
            name='Agency_jp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=255)),
                ('agency_official_name', models.CharField(max_length=255, null=True)),
                ('agency_zip_number', models.CharField(max_length=255, null=True)),
                ('agency_address', models.CharField(max_length=255, null=True)),
                ('agency_president_pos', models.CharField(max_length=255, null=True)),
                ('agency_president_name', models.CharField(max_length=255, null=True)),
                ('agency_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrant'),
        ),
        migrations.AddConstraint(
            model_name='trips',
            constraint=models.UniqueConstraint(fields=('trip_id', 'registrant'), name='unique_trips'),
        ),
        migrations.AddConstraint(
            model_name='stops',
            constraint=models.UniqueConstraint(fields=('stop_id', 'registrant'), name='unique_stops'),
        ),
        migrations.AddConstraint(
            model_name='shapes',
            constraint=models.UniqueConstraint(fields=('id', 'registrant'), name='unique_shapes'),
        ),
        migrations.AddConstraint(
            model_name='routes_jp',
            constraint=models.UniqueConstraint(fields=('id', 'registrant'), name='unique_route_jp'),
        ),
        migrations.AddConstraint(
            model_name='routes',
            constraint=models.UniqueConstraint(fields=('route_id', 'agency_obj'), name='unique_routes'),
        ),
        migrations.AddConstraint(
            model_name='office_jp',
            constraint=models.UniqueConstraint(fields=('office_id', 'registrant'), name='unique_office_jp'),
        ),
        migrations.AddConstraint(
            model_name='fare_rules',
            constraint=models.UniqueConstraint(fields=('fare_id', 'route_id', 'origin_id', 'destination_id', 'registrant'), name='unique_fare_rules'),
        ),
        migrations.AddConstraint(
            model_name='fare_attributes',
            constraint=models.UniqueConstraint(fields=('fare_id', 'currency_type', 'registrant'), name='unique_fare_attributes'),
        ),
        migrations.AddConstraint(
            model_name='calendar_dates',
            constraint=models.UniqueConstraint(fields=('service_id', 'date', 'registrant'), name='unique_calendar_dates'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('service_id', 'registrant'), name='unique_calendar'),
        ),
        migrations.AddConstraint(
            model_name='agency_jp',
            constraint=models.UniqueConstraint(fields=('agency_id', 'registrant'), name='unique_agency_jp'),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('agency_id', 'registrant'), name='unique_agency'),
        ),
    ]
