# Generated by Django 3.2.23 on 2023-12-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='bikes_allowed',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='wheelchair_accessible',
        ),
    ]
