# Generated by Django 3.2.23 on 2023-12-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231227_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyjp',
            name='agency_email',
        ),
        migrations.RemoveField(
            model_name='agencyjp',
            name='agency_fare_url',
        ),
        migrations.RemoveField(
            model_name='agencyjp',
            name='agency_lang',
        ),
        migrations.RemoveField(
            model_name='agencyjp',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='agencyjp',
            name='agency_phone',
        ),
        migrations.RemoveField(
            model_name='agencyjp',
            name='agency_timezone',
        ),
        migrations.RemoveField(
            model_name='agencyjp',
            name='agency_url',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='feed_contact_email',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='feed_contact_phone',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='feed_contact_url',
        ),
        migrations.AddField(
            model_name='agencyjp',
            name='agency_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyjp',
            name='agency_official_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyjp',
            name='agency_president_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyjp',
            name='agency_president_pos',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyjp',
            name='agency_zip_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_fare_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fare_attributes',
            name='transfer_duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fare_rules',
            name='contains_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fare_rules',
            name='destination_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fare_rules',
            name='origin_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fare_rules',
            name='route_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='feed_end_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='feed_start_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedinfo',
            name='feed_version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frequencies',
            name='exact_times',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='office_jp',
            name='office_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='office_jp',
            name='office_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='route_jp',
            name='destination_stop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='route_jp',
            name='origin_stop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='route_jp',
            name='route_update_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='route_jp',
            name='via_stop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_long_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_short_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_text_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shapes',
            name='shape_dist_traveled',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='drop_off_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='pickup_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='shape_dist_traveled',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='stop_headsign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stop_times',
            name='timepoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='parent_station',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='platform_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='zone_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='min_transfer_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='block_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='direction_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='jp_trip_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='shape_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_headsign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_short_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
