# Generated by Django 3.2.23 on 2023-12-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231227_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop_times',
            name='shape_dist_traveled',
        ),
    ]
