# Generated by Django 3.2.23 on 2023-12-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_stop_times_shape_dist_traveled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare_attributes',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fare_attributes',
            name='transfer_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
