# Generated by Django 3.2.23 on 2023-12-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_fare_rules_contains_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapes',
            name='shape_dist_traveled',
        ),
    ]
