# Generated by Django 3.2.23 on 2023-12-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_shapes_shape_dist_traveled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('trans_id', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=255)),
                ('record_id', models.CharField(max_length=255)),
                ('record_sub_id', models.CharField(max_length=255)),
            ],
        ),
    ]
