# Generated by Django 3.2.23 on 2023-12-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_translations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translations',
        ),
    ]
